version: "3.8"

services:
  postgis:
    image: postgis/postgis:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  osm2pgsql:
    image: iboates/osm2pgsql:latest
    environment:
      PGPASSWORD: ${PGPASSWORD}

volumes:
  postgis_data:
