version: "3.8"

services:
  postgis:
    image: docker.io/postgis/postgis:latest
    environment:
      POSTGRES_DB: ${OSM_DB_NAME}
      POSTGRES_USER: ${OSM_DB_USER}
      POSTGRES_PASSWORD: ${OSM_DB_PASSWORD}
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - "${OSM_DB_PORT}:5432"
    network_mode: host

  osm2pgsql:
    image: docker.io/iboates/osm2pgsql:latest
    environment:
      PGPASSWORD: ${OSM_DB_PASSWORD}
    volumes:
      - ./data:/data
      - ./osm2pgsql:/osm2pgsql
    network_mode: host

volumes:
  postgis_data:
